pipeline {
    agent any
    stages {
        stage('docker run MySQL image') {
             steps {
                 sh "docker run --name mysql-my_movie_plan -e MYSQL_ROOT_PASSWORD=admin@root -e MYSQL_DATABASE=my_movie_plan -e MYSQL_USER=root -e MYSQL_PASSWORD=Spra@$123 -d mysql:latest"
             }
        }

        stage('docker images') {
             steps {
                 sh "docker images"
             }
        }
    }
}